name: Send Email Notification

on:
  schedule:
    # ตั้งเวลาให้รันทุกวันตอนเวลา 07:00 น. UTC
    - cron: '0 7 * * *'
  workflow_dispatch:  # ให้สามารถรันด้วยตนเองได้ผ่าน GitHub UI

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client smtplib

      - name: Run the script
        run: |
          python NotifySheet.py
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
